# Generated by Django 4.2.11 on 2024-06-18 12:04

from django.db import DataError, migrations, models
import django.db.models.deletion


def validate_no_missing_catalogus_fields(apps, schema_editor):
    ZaakTypeConfig = apps.get_model("openzaak", "ZaakTypeConfig")

    if rows_with_missing_catalogus := ZaakTypeConfig.objects.filter(
        catalogus__isnull=True
    ).count():
        raise DataError(
            f"Your database contains {rows_with_missing_catalogus} ZaakTypeConfig"
            " row(s) with a missing `catalogus` field. This field is now required:"
            " please manually update all the affected rows or re-sync your ZGW"
            " objects to ensure the field is included."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("openzaak", "0052_add_catalogusconfig_service"),
    ]

    operations = [
        migrations.RunPython(
            validate_no_missing_catalogus_fields,
            reverse_code=lambda *args, **kwargs: None,
        ),
        migrations.AlterField(
            model_name="zaaktypeconfig",
            name="catalogus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="openzaak.catalogusconfig",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="zaaktypeconfig",
            name="unique_identificatie_in_catalogus",
        ),
        migrations.RemoveConstraint(
            model_name="zaaktypeconfig",
            name="unique_identificatie_without_catalogus",
        ),
        migrations.AddConstraint(
            model_name="zaaktypeconfig",
            constraint=models.UniqueConstraint(
                fields=("catalogus", "identificatie"),
                name="unique_identificatie_in_catalogus",
            ),
        ),
    ]
